### ISSUE TITLE
Confusing Verbage on Animations

### ISSUE THREAD

**Issue by RedDwarfian** [jtenner/ns.js#1]
> ```center_stage``` - Place the bottom middle of the sprite on the bottom middle of the screen.
> ...
> ```left_3```, ```right_3``` - When three characters are on the screen, this is the left and right position for actors. Use with ```center``` on the third character.

Not sure if ```center_stage``` and ```center``` are two different keywords.

**Comment by jtenner** [comment]
Thank you.

**Comment by jtenner** [comment]
The keyword should be `center_stage`.

> left_3, right_3 - When three characters are on the screen, this is the left and right position for actors. Use with `center_stage` on the third character.

**Comment by jtenner** [comment]
I'll also clarify that it's an `animation`.

Thanks.

**Comment by jtenner** [comment]
This is now fixed.
