### ISSUE TITLE
So is the variable 'a' a character or a string?

### ISSUE THREAD

**Issue by RedDwarfian** [jtenner/ns.js#2]
label move_aya:
      a "I am not here yet, but I will be soon!"
    
      show a
        run center_stage
        run fade_in

It isn't clear that the "move_aya" action is being defined by the label command, nor is it clear whether or not these are separate actions that require separate clicks.  Moreover, it's unclear what line 2 does, and how it interacts with line 4.  Does line 2 display the text, and then line 4 starts the animation sequence for the sprite, or does line 4 need to be in there in order for line 2's text to be displayed?

Suggestion (if I am interpreting the code correctly; place this after the list of presets, in place of "For example, using the ```run``` keyword to attach an animation to a character:"):

By using the ```run``` keyword, and declaring a position, you can move the character to the specified location.

## Keyframes!

// Insert Keyframes section here

## Do all the things!

The ```show``` keyword attaches the character to the novel, and is required for the ```run``` keyword to function. It is also possible to run mutliple animations at once.

// Insert code from above

Whenever ```move_aya``` is called, Aya will display the text "I am not here yet, but I will be soon!", and then simultaneously move her from wherever she is to the center, and fade her ```alpha``` to 1 from whatever it had been.

**Comment by RedDwarfian** [comment]
You should also have a comment somewhere that says "```character``` labels can be used in place of the ```"Speaker"``` string.  It will display the character's name as the speaker.

**Comment by jtenner** [comment]
That is for the "text" section, probably not something to worry about here.

**Comment by jtenner** [comment]
I believe I have made enough changes to this.  Not sure if it's completed. I'll make a commit and ask for your help.
